image: golang:1.24

stages:
  - test
  - build

format:
  stage: test
  script:
    # - go fmt $(go list ./... | grep -v /vendor/)
    # - go vet $(go list ./... | grep -v /vendor/)
    # - go test -race $(go list ./... | grep -v /vendor/)
    gofmt -l -d *.go

compile:
  stage: build
  before_script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}.insteadOf https://${CI_SERVER_HOST}
    - export GOPRIVATE=${CI_SERVER_HOST}
  script:
    - mkdir -p mybinaries
    - go build -o mybinaries ./...
  artifacts:
    paths:
      - mybinaries

