[package]
name = "songparser"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
futures = { version = "0.3.31" }
reqwest = { version = "0.12.19", features = ["json", "stream"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139" }
uuid = { version = "1.16.0", features = ["v4", "serde"] }
dotenvy = { version = "0.15.7" }
icarus_models = { git = "ssh://git@git.kundeng.us/phoenix/icarus_models.git", tag = "v0.4.3" }
icarus_envy = { git = "ssh://git@git.kundeng.us/phoenix/icarus_envy.git", tag = "v0.2.0" }
