[package]
name = "songparser"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
reqwest = { version = "0.12.19" }
dotenvy = { version = "0.15.7" }
icarus_models = { git = "ssh://git@git.kundeng.us/phoenix/icarus_models.git", tag = "v0.4.3" }
