version: '3.8' # Use a recent version

services:
  songparser:
    build:
      context: .
      ssh: ["default"]
    container_name: songparser
    env_file:
      - .env
    restart: unless-stopped
